"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OSWAP_OracleUnity = exports.OSWAP_OracleSigned = exports.OSWAP_OracleSetYourOwnPrice = exports.OSWAP_OracleConstantLimited = exports.OSWAP_OracleConstant = exports.OSWAP_OracleChainlinkPriceGuardFiatBinance = exports.OSWAP_OracleChainlinkPriceGuardBinance = exports.OSWAP_OracleChainlinkLimited = exports.OSWAP_OracleChainlinkFiatBinance = exports.OSWAP_OracleChainlinkFiat = exports.OSWAP_OracleChainlinkBinance = exports.OSWAP_OracleChainlink = exports.OSWAP_OracleChained = void 0;
var OSWAP_OracleChained_1 = require("./OSWAP_OracleChained");
Object.defineProperty(exports, "OSWAP_OracleChained", { enumerable: true, get: function () { return OSWAP_OracleChained_1.OSWAP_OracleChained; } });
var OSWAP_OracleChainlink_1 = require("./OSWAP_OracleChainlink");
Object.defineProperty(exports, "OSWAP_OracleChainlink", { enumerable: true, get: function () { return OSWAP_OracleChainlink_1.OSWAP_OracleChainlink; } });
var OSWAP_OracleChainlinkBinance_1 = require("./OSWAP_OracleChainlinkBinance");
Object.defineProperty(exports, "OSWAP_OracleChainlinkBinance", { enumerable: true, get: function () { return OSWAP_OracleChainlinkBinance_1.OSWAP_OracleChainlinkBinance; } });
var OSWAP_OracleChainlinkFiat_1 = require("./OSWAP_OracleChainlinkFiat");
Object.defineProperty(exports, "OSWAP_OracleChainlinkFiat", { enumerable: true, get: function () { return OSWAP_OracleChainlinkFiat_1.OSWAP_OracleChainlinkFiat; } });
var OSWAP_OracleChainlinkFiatBinance_1 = require("./OSWAP_OracleChainlinkFiatBinance");
Object.defineProperty(exports, "OSWAP_OracleChainlinkFiatBinance", { enumerable: true, get: function () { return OSWAP_OracleChainlinkFiatBinance_1.OSWAP_OracleChainlinkFiatBinance; } });
var OSWAP_OracleChainlinkLimited_1 = require("./OSWAP_OracleChainlinkLimited");
Object.defineProperty(exports, "OSWAP_OracleChainlinkLimited", { enumerable: true, get: function () { return OSWAP_OracleChainlinkLimited_1.OSWAP_OracleChainlinkLimited; } });
var OSWAP_OracleChainlinkPriceGuardBinance_1 = require("./OSWAP_OracleChainlinkPriceGuardBinance");
Object.defineProperty(exports, "OSWAP_OracleChainlinkPriceGuardBinance", { enumerable: true, get: function () { return OSWAP_OracleChainlinkPriceGuardBinance_1.OSWAP_OracleChainlinkPriceGuardBinance; } });
var OSWAP_OracleChainlinkPriceGuardFiatBinance_1 = require("./OSWAP_OracleChainlinkPriceGuardFiatBinance");
Object.defineProperty(exports, "OSWAP_OracleChainlinkPriceGuardFiatBinance", { enumerable: true, get: function () { return OSWAP_OracleChainlinkPriceGuardFiatBinance_1.OSWAP_OracleChainlinkPriceGuardFiatBinance; } });
var OSWAP_OracleConstant_1 = require("./OSWAP_OracleConstant");
Object.defineProperty(exports, "OSWAP_OracleConstant", { enumerable: true, get: function () { return OSWAP_OracleConstant_1.OSWAP_OracleConstant; } });
var OSWAP_OracleConstantLimited_1 = require("./OSWAP_OracleConstantLimited");
Object.defineProperty(exports, "OSWAP_OracleConstantLimited", { enumerable: true, get: function () { return OSWAP_OracleConstantLimited_1.OSWAP_OracleConstantLimited; } });
var OSWAP_OracleSetYourOwnPrice_1 = require("./OSWAP_OracleSetYourOwnPrice");
Object.defineProperty(exports, "OSWAP_OracleSetYourOwnPrice", { enumerable: true, get: function () { return OSWAP_OracleSetYourOwnPrice_1.OSWAP_OracleSetYourOwnPrice; } });
var OSWAP_OracleSigned_1 = require("./OSWAP_OracleSigned");
Object.defineProperty(exports, "OSWAP_OracleSigned", { enumerable: true, get: function () { return OSWAP_OracleSigned_1.OSWAP_OracleSigned; } });
var OSWAP_OracleUnity_1 = require("./OSWAP_OracleUnity");
Object.defineProperty(exports, "OSWAP_OracleUnity", { enumerable: true, get: function () { return OSWAP_OracleUnity_1.OSWAP_OracleUnity; } });
