// SPDX-License-Identifier: GPL-3.0-only
pragma solidity 0.6.11;

import "../contracts/OSWAP_OracleChainlinkFiatBase.sol";
import "../contracts/OSWAP_OracleChainlinkPriceGuardBinance.sol";
import "../contracts/OSWAP_OracleChainlinkPriceGuardBase.sol";
import "../contracts/OSWAP_OracleChainlinkFiatBinance.sol";
import "../contracts/OSWAP_OracleChainlinkLimitedBase.sol";
import "../contracts/OSWAP_OracleChainlinkPriceGuardFiatBinance.sol";
import "../contracts/OSWAP_OracleConstantLimited.sol";
import "../contracts/OSWAP_OracleSetYourOwnPrice.sol";
import "../contracts/OSWAP_OracleChainlinkBase.sol";
import "../contracts/OSWAP_OracleChainlinkBinance.sol";
import "../contracts/OSWAP_OracleChainlinkLimited.sol";
import "../contracts/OSWAP_OracleChainlinkPriceGuardFiatBase.sol";
import "../contracts/libraries/Ownable.sol";
import "../contracts/libraries/SafeMath.sol";
import "../contracts/libraries/Context.sol";
import "../contracts/OSWAP_OracleConstant.sol";
import "../contracts/interfaces/IPair.sol";
import "../contracts/interfaces/IOSWAP_OracleAdaptorPriceGuard.sol";
import "../contracts/interfaces/IFactory.sol";
import "../contracts/interfaces/AggregatorV3Interface.sol";
import "../contracts/interfaces/IERC20.sol";
import "../contracts/interfaces/IOSWAP_OracleScoreOracleAdaptor.sol";
import "../contracts/interfaces/ICertiKSecurityOracle.sol";
import "../contracts/interfaces/IOSWAP_OracleAdaptor.sol";
import "../contracts/OSWAP_OracleChainlinkFiat.sol";
import "../contracts/OSWAP_OracleChainlinkV1Base.sol";
import "../contracts/OSWAP_OracleChainlink.sol";
import "../contracts/OSWAP_OracleChained.sol";
import "../contracts/OSWAP_OracleUnity.sol";
import "../contracts/OSWAP_OracleSigned.sol";
